<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FBS.Core\FBS.Core.csproj" />
    <ProjectReference Include="..\FBS.Infrastructure\FBS.Infrastructure.csproj" />
  </ItemGroup>

</Project>
